name: Publish Porxy Package

on:
  push:
    branches: [feat/api-provider-proxy*]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get cache date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: packages/mask/node_modules/.cache/
          key: ${{ runner.os }}-extension-${{ hashFiles('pnpm-lock.yaml') }}-${{ steps.get-date.outputs.date }}
          restore-keys: ${{ runner.os }}-extension-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install
      - run: pnpm build
      - name: Run provider-proxy package build
        working-directory: ./packages/provider-proxy
        run: pnpm install && pnpm build
      - name: Publish to github npm pkg
        run: npm publish ./packages/provider-proxy/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
